name: Our Workflow
on: 
  push:
    branches: [ main ]
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: gradlew 실행권한 설정
        run: chmod +x gradlew
          
      - name: build gradlew
        run: ./gradlew bootJar
      
      - name: docker image build
        run: docker build -t yoo07134/hello-web:latest .
        
      - name: docker hub login
        uses: docker/login-action@v1
        with: 
          username: ${{ secret.USERNAME }}
          password: ${{ secret.PASSWORD }}
          
      - name: docker hun push
        run: docker push yoo07134/hello-web:latest
        
      